### ISSUE TITLE
Nested foreach()-blocks handled incorrectly

### ISSUE THREAD

**Issue by VolkerStolz** [abstools/abstools#270] opened 2020-01-21 17:56 UTC
Test case forthcoming.

```
org.abs_models.common.NotImplementedYetException: abstools/frontend/src/test/resources/abssamples/backend/StmtTests/foreach-nested.abs:8:1:The AST class org.abs_models.frontend.ast.ForeachStmt is not implemented yet
	at org.abs_models.frontend.ast.Stmt.generateErlangCode(Stmt.java:125)
```

**Comment by VolkerStolz** [comment] 2020-01-21 18:04
Prettyprinting fails in a different manner:

```
$ bin/bash/absc --prettyprint src/test//resources/abssamples/backend/StmtTests/foreach-nested.abs 
module BackendTest;




{
  Bool testresult = False;
  Int sum = 0;
  List<List<Int>> l = list[list[1, 2, 3]];
  {
    ABS.StdLib.List<ABS.StdLib.List<ABS.StdLib.Int>> tmp1382756158 = l;
    while (! isEmpty(tmp1382756158)) {
      ABS.StdLib.List<ABS.StdLib.Int> elem = head(tmp1382756158);
      tmp1382756158 = tail(tmp1382756158);
      {
        foreach (x in elem) {
          sum = ( sum + x );
        }
      }
    }
  }
  testresult = ( sum == 6 );
}
```

**Comment by rudi** [comment] 2020-01-22 09:42
Thanks for reporting. Transferring your test case to here:

```
module BackendTest;

{
    Bool testresult = False;
    Int sum = 0;
    List<List<Int>> l = list[list[1, 2, 3]];
    foreach (elem in l) {
	foreach (x in elem) {
        sum = sum +  x;
}
    }
    testresult = sum == 6;
}
```

**Comment by rudi** [comment] 2020-01-22 09:50
The root cause is line 108 of `ForeachExpander.jadd`:

```
            whilebody.addStmt(getBody().treeCopyNoTransform());
```

Anything inside `getBody()` will not be processed since we basically modify an iterator (Line 25 of the same file).  I'll check if it works if we re-use the current block instead of transforming it.

**Closed** 2020-01-22 10:14 UTC
Labels: bug
